coverage:
    precision: 2
    round: down
    range: 20..80
    status:
        project:
            backend:
                target: 80%
                threshold: 0%
                informational: false
                if_ci_failed: error
                flags:
                    - backend
                paths:
                    - backend/src/
            frontend:
                target: 80%
                threshold: 0%
                informational: false
                if_ci_failed: error
                flags:
                    - frontend
                paths:
                    - src/
        patch:
            backend:
                target: 80%
                threshold: 0%
                informational: false
                if_ci_failed: error
                flags:
                    - backend
                paths:
                    - backend/src/
            frontend:
                target: 80%
                threshold: 0%
                informational: false
                if_ci_failed: error
                flags:
                    - frontend
                paths:
                    - src/

comment:
    layout: "reach,diff,flags,tree"
    behavior: default
    require_changes: false

flags:
    frontend:
        paths:
            - src/
    backend:
        paths:
            - backend/src/
