import { defineConfig } from "vitest/config";

export default defineConfig({
    test: {
        environment: "jsdom",
        globals: false,
        setupFiles: ["src/test/setup.ts"],
        maxWorkers: 2,
        include: ["src/**/*.test.ts", "src/**/*.test.tsx"],
        coverage: {
            provider: "v8",
            reporter: ["text", "lcov"],
            include: [
                "src/utils/**/*.{ts,tsx}",
                "src/components/ui/**/*.{ts,tsx}",
                "src/hooks/**/*.{ts,tsx}",
                "src/stores/**/*.{ts,tsx}",
                "src/collections/**/*.{ts,tsx}",
                "src/lib/**/*.{ts,tsx}",
                "src/components/features/agents/AgentCard.tsx",
                "src/components/features/agents/StatusIndicator.tsx",
                "src/components/features/agents/TaskHistorySidebar.tsx",
                "src/components/features/agents/status.ts",
                "src/components/features/chat/chatRuntime.ts",
                "src/components/features/chat/chatTypes.ts",
                "src/components/features/chat/chatUtils.ts",
                "src/components/features/chat/slashCommands.ts",
                "src/components/features/dashboard/CacheStatusCard.tsx",
                "src/components/features/dashboard/CronOverviewCard.tsx",
                "src/components/features/dashboard/GitOverviewCard.tsx",
                "src/components/features/dashboard/LogRotationCard.tsx",
                "src/components/features/dashboard/QuotaOverviewCard.tsx",
                "src/components/features/database/AutovacuumHealthTable.tsx",
                "src/components/features/database/DatabaseOverviewCards.tsx",
                "src/components/features/database/DatabaseSizesTable.tsx",
                "src/components/features/database/DatabaseTableShell.tsx",
                "src/components/features/database/TopQueriesTable.tsx",
                "src/components/features/database/databaseUtils.ts",
                "src/components/features/docker/DockerContainersTable.tsx",
                "src/components/features/docker/DockerImagesTable.tsx",
                "src/components/features/docker/DockerVolumesTable.tsx",
                "src/components/features/docker/dockerFormatters.ts",
                "src/components/features/files/fileConstants.ts",
                "src/components/features/logs/LevelFilter.tsx",
                "src/components/features/logs/LogLine.tsx",
                "src/components/features/sessions/LiveFeedRow.tsx",
                "src/components/features/sessions/MessageBubble.tsx",
                "src/components/features/sessions/SessionActionsDropdown.tsx",
                "src/components/features/sessions/SessionStatsBar.tsx",
                "src/components/features/settings/ChannelSection.tsx",
                "src/components/features/settings/HeartbeatSection.tsx",
                "src/components/features/settings/ModelSection.tsx",
                "src/components/features/settings/SecuritySection.tsx",
                "src/components/features/settings/SessionSection.tsx",
                "src/components/features/settings/SkillsSection.tsx",
                "src/components/features/settings/ToolSection.tsx",
                "src/components/features/settings/toolCatalog.ts",
            ],
            exclude: ["src/**/*.test.{ts,tsx}", "src/**/index.ts"],
        },
    },
});
