[test]
root = ["src", "test"]
preload = ["./test/setup.ts"]
coverageReporter = ["text", "lcov"]
coverageDirectory = "coverage"
coverageSkipTestFiles = true
coveragePathIgnorePatterns = [
    "dist/**",
    "test/**",
    "src/**/*.d.ts",
]
