import type { DashboardRouteDocumentation } from "../src/shared/browserRouteRegistry.ts";

export interface DashboardPageStoryRequirement {
    readonly exports: readonly string[];
    readonly file: string;
    readonly path: DashboardRouteDocumentation["path"];
    readonly title: `Pages/${string}`;
}

/** Required material full-page states for every production browser route. */
export const dashboardPageStoryRequirements = Object.freeze([
    {
        exports: [
            "FreshPopulated",
            "Empty",
            "PartialUnavailable",
            "LastKnownGood",
            "RefreshQueued",
        ],
        file: "src/browser/overview/stories/OverviewRoute.stories.tsx",
        path: "/",
        title: "Pages/Dashboard",
    },
    {
        exports: [
            "Loading",
            "Ready",
            "InitialError",
            "DestructiveConfirmation",
            "EnrollmentSecret",
        ],
        file: "src/browser/security/stories/AccountSecurityRoute.stories.tsx",
        path: "/account-security",
        title: "Pages/Account security",
    },
    {
        exports: [
            "DashboardTab",
            "OpenClawFresh",
            "PartialStale",
            "ConfigurationUnavailable",
            "MutationBusy",
            "MutationError",
            "RestartRecovery",
        ],
        file: "src/browser/settings/stories/SettingsRoute.stories.tsx",
        path: "/settings",
        title: "Pages/Settings",
    },
    {
        exports: ["Loading", "Ready", "EmptyHistory", "InitialError", "BrowserRetained"],
        file: "src/browser/agents/stories/AgentsRoute.stories.tsx",
        path: "/agents",
        title: "Pages/Agents",
    },
    {
        exports: [
            "PopulatedStreaming",
            "Empty",
            "LastKnownGood",
            "DisconnectedDraft",
            "InitialError",
            "AttachmentBusy",
            "VoiceBusy",
            "Mobile",
        ],
        file: "src/browser/chat/stories/ChatRoute.stories.tsx",
        path: "/chat",
        title: "Pages/Chat",
    },
    {
        exports: [
            "Loading",
            "Fresh",
            "MaintenanceAttention",
            "LastKnownGood",
            "BrowserRetained",
            "PartialUnavailable",
            "Unavailable",
        ],
        file: "src/browser/database/stories/DatabaseRoute.stories.tsx",
        path: "/database",
        title: "Pages/Database",
    },
    {
        exports: [
            "Loading",
            "Populated",
            "EmptyReadOnly",
            "InitialError",
            "BrowserRetained",
            "MutationBusy",
            "MutationConflict",
            "Mobile",
        ],
        file: "src/browser/files/stories/FilesRoute.stories.tsx",
        path: "/files",
        title: "Pages/Files",
    },
    {
        exports: [
            "Loading",
            "Fresh",
            "Empty",
            "LastKnownGood",
            "Unavailable",
            "UpdatesAvailable",
            "Confirmation",
            "PrunePreview",
            "Logs",
            "Queued",
            "UnknownOutcome",
            "Error",
        ],
        file: "src/browser/docker/stories/DockerRoute.stories.tsx",
        path: "/docker",
        title: "Pages/Docker",
    },
    {
        exports: [
            "Loading",
            "PullRequests",
            "Empty",
            "LastKnownGood",
            "BrowserRetained",
            "PartialUnavailable",
            "PreviewRunning",
            "PreviewContention",
            "ActionActive",
            "Confirmation",
            "Queued",
            "UnknownOutcome",
            "Error",
            "RollbackBlocked",
        ],
        file: "src/browser/delivery/stories/DeliveryRoute.stories.tsx",
        path: "/delivery",
        title: "Pages/Delivery",
    },
    {
        exports: [
            "Loading",
            "List",
            "Empty",
            "InitialError",
            "BrowserRetained",
            "SelectedDetail",
            "DetailWithListUnavailable",
        ],
        file: "src/browser/monitoring/stories/IncidentsRoute.stories.tsx",
        path: "/incidents",
        title: "Pages/Incidents",
    },
    {
        exports: [
            "Loading",
            "DashboardJobs",
            "OpenClawSchedules",
            "Empty",
            "InitialError",
            "BrowserRetained",
            "RunDetail",
            "ScheduleDetail",
            "Busy",
            "Confirmation",
            "Queued",
            "UnknownOutcome",
        ],
        file: "src/browser/jobs/stories/JobsRoute.stories.tsx",
        path: "/jobs",
        title: "Pages/Jobs",
    },
    {
        exports: [
            "Loading",
            "Unavailable",
            "Bootstrap",
            "Password",
            "PendingTotp",
            "RecoveryCode",
            "WebAuthn",
            "ProofError",
        ],
        file: "src/browser/auth/stories/LoginRoute.stories.tsx",
        path: "/login",
        title: "Pages/Login",
    },
    {
        exports: [
            "Loading",
            "Fresh",
            "EmptySearch",
            "InitialError",
            "BrowserRetained",
            "MaintenanceUnavailable",
            "Confirmation",
            "Busy",
            "Queued",
            "Error",
            "Mobile",
        ],
        file: "src/browser/logs/stories/LogsRoute.stories.tsx",
        path: "/logs",
        title: "Pages/Logs",
    },
    {
        exports: [
            "Loading",
            "FreshFeed",
            "Posts",
            "Comments",
            "Empty",
            "LastKnownGood",
            "BrowserRetained",
            "InitialError",
        ],
        file: "src/browser/moltbook/stories/MoltbookRoute.stories.tsx",
        path: "/moltbook",
        title: "Pages/Moltbook",
    },
    {
        exports: [
            "Loading",
            "List",
            "Empty",
            "InitialError",
            "BrowserRetained",
            "SelectedReport",
            "DetailWithListUnavailable",
            "DeleteConfirmation",
            "DeletePrecondition",
            "DeleteError",
        ],
        file: "src/browser/monitoring/stories/ReportsRoute.stories.tsx",
        path: "/reports",
        title: "Pages/Reports",
    },
    {
        exports: [
            "Loading",
            "Fresh",
            "Empty",
            "LastKnownGood",
            "InitialError",
            "BackgroundUnavailable",
            "ActionBusy",
            "UnknownOutcome",
            "Mobile",
        ],
        file: "src/browser/sessions/stories/GatewaySessionsRoute.stories.tsx",
        path: "/sessions",
        title: "Pages/Sessions",
    },
    {
        exports: [
            "Loading",
            "Board",
            "Empty",
            "FilteredEmpty",
            "InitialError",
            "Busy",
            "Error",
            "CreateModal",
            "DetailModal",
            "Mobile",
        ],
        file: "src/browser/tasks/stories/TasksRoute.stories.tsx",
        path: "/tasks",
        title: "Pages/Tasks",
    },
    {
        exports: [
            "Ready",
            "Connected",
            "Reconnecting",
            "ReplayGap",
            "ActiveElsewhere",
            "DockerHandoff",
            "Unavailable",
            "MfaError",
            "Mobile",
        ],
        file: "src/browser/terminal/stories/TerminalRoute.stories.tsx",
        path: "/terminal",
        title: "Pages/Terminal",
    },
] as const satisfies readonly DashboardPageStoryRequirement[]);
