import type {
    ContractAccess,
    ProcedureContract,
    RawHttpContract,
    RealtimeEventContract,
} from "../../src/contracts/registry.ts";

function accessLabel(access: ContractAccess): string {
    return access.kind === "public"
        ? "Public"
        : `Authenticated: ${access.capabilities.join(", ")}`;
}

function documentHeader(title: string, source: string): string {
    return `# ${title}\n\n> Generated by \`${source}\`. Do not edit manually.\n\n`;
}

/**
 * Renders the generated documentation index.
 * @returns Generated Markdown index.
 */
export function renderGeneratedIndex(): string {
    return `${documentHeader("Generated Dashboard Reference", "bun run docs:generate")}- [tRPC procedures](procedures.md)\n- [Raw HTTP routes](raw-http.md)\n- [Realtime events](realtime-events.md)\n- [Packages and runtime](packages-and-runtime.md)\n- [Transport schemas](schemas/)\n`;
}

/**
 * Renders procedure contracts as Markdown.
 * @param contracts Implemented procedure contracts.
 * @returns Generated Markdown document.
 */
export function renderProcedures(contracts: readonly ProcedureContract[]): string {
    const rows = contracts
        .toSorted((left, right) => left.name.localeCompare(right.name))
        .map(
            (contract) =>
                `| \`${contract.name}\` | ${contract.kind} | ${contract.domain} | ${accessLabel(contract.access)} | [input](./schemas/${contract.inputSchemaId}.schema.json) | [output](./schemas/${contract.outputSchemaId}.schema.json) | ${contract.summary} |`
        );

    return `${documentHeader("tRPC Procedures", "bun run docs:generate")}| Procedure | Kind | Domain | Access | Input | Output | Summary |\n| --- | --- | --- | --- | --- | --- | --- |\n${rows.join("\n")}\n`;
}

/**
 * Renders raw HTTP route contracts as Markdown.
 * @param contracts Implemented raw HTTP contracts.
 * @returns Generated Markdown document.
 */
export function renderRawHttp(contracts: readonly RawHttpContract[]): string {
    const rows = contracts
        .toSorted((left, right) =>
            `${left.path}:${left.method}`.localeCompare(`${right.path}:${right.method}`)
        )
        .map(
            (contract) =>
                `| ${contract.method} | \`${contract.path}\` | ${accessLabel(contract.access)} | ${contract.statusCodes.join(", ")} | [response](./schemas/${contract.responseSchemaId}.schema.json) | ${contract.summary} |`
        );

    return `${documentHeader("Raw HTTP Routes", "bun run docs:generate")}| Method | Path | Access | Status | Response | Summary |\n| --- | --- | --- | --- | --- | --- |\n${rows.join("\n")}\n`;
}

/**
 * Renders realtime topic contracts as Markdown.
 * @param contracts Implemented realtime contracts.
 * @returns Generated Markdown document.
 */
export function renderRealtimeEvents(
    contracts: readonly RealtimeEventContract[]
): string {
    const rows = contracts
        .toSorted((left, right) => left.topic.localeCompare(right.topic))
        .map(
            (contract) =>
                `| \`${contract.topic}\` | [payload](./schemas/${contract.payloadSchemaId}.schema.json) | \`${contract.snapshotProcedure}\` | ${contract.retention} | ${contract.summary} |`
        );
    const body =
        rows.length === 0
            ? "No realtime topics are implemented in the current foundation slice.\n"
            : `| Topic | Payload | Snapshot | Retention | Summary |\n| --- | --- | --- | --- | --- |\n${rows.join("\n")}\n`;

    return `${documentHeader("Realtime Events", "bun run docs:generate")}${body}`;
}

/** Direct dependency sections and Bun policy needed by generated documentation. */
export interface PackageDocumentationInput {
    dependencies: Readonly<Record<string, string>>;
    developmentDependencies: Readonly<Record<string, string>>;
    resolvedVersions: Readonly<Record<string, string>>;
    runtime: {
        channel: string;
        version: string;
    };
}

function packageRows(
    packages: Readonly<Record<string, string>>,
    resolvedVersions: Readonly<Record<string, string>>,
    scope: string
): string[] {
    return Object.entries(packages)
        .toSorted(([left], [right]) => left.localeCompare(right))
        .map(([name, declared]) => {
            const resolved = resolvedVersions[name];
            if (!resolved) {
                throw new Error(
                    `Direct package is missing from the Bun lockfile: ${name}`
                );
            }
            return `| \`${name}\` | \`${declared}\` | \`${resolved}\` | ${scope} |`;
        });
}

/**
 * Renders the runtime policy and exact direct package facts as Markdown.
 * @param input Runtime policy and package manifests.
 * @returns Generated Markdown document.
 */
export function renderPackagesAndRuntime(input: PackageDocumentationInput): string {
    const packageTable = [
        ...packageRows(input.dependencies, input.resolvedVersions, "runtime"),
        ...packageRows(
            input.developmentDependencies,
            input.resolvedVersions,
            "development"
        ),
    ].join("\n");

    return `${documentHeader("Packages and Runtime", "bun run docs:generate")}## Bun\n\n| Fact | Value |\n| --- | --- |\n| Repository channel | \`${input.runtime.channel}\` |\n| Required runtime version | \`${input.runtime.version}\` |\n| Release identity | Exact revision recorded by each immutable release |\n\n## Direct packages\n\n| Package | Declared | Resolved | Scope |\n| --- | --- | --- | --- |\n${packageTable}\n`;
}
