import type {
    ContractAccess,
    ProcedureContract,
    RawHttpBodyContract,
    RawHttpContract,
    RealtimeEventContract,
} from "../../src/contracts/registry.ts";

function authenticatedPrincipalLabel(
    capabilities: readonly string[],
    principalKinds?: readonly ("automation" | "session")[]
): string {
    const principalKind = principalKinds?.length === 1 ? principalKinds[0] : undefined;
    if (principalKind !== undefined) {
        const principalLabel =
            principalKind === "session" ? "browser session" : "automation principal";
        return capabilities.length === 0
            ? `Authenticated ${principalLabel}`
            : `Authenticated ${principalLabel}: ${capabilities.join(", ")}`;
    }
    return capabilities.length === 0
        ? "Authenticated"
        : `Authenticated: ${capabilities.join(", ")}`;
}

function accessLabel(access: ContractAccess): string {
    switch (access.kind) {
        case "public": {
            return "Public";
        }
        case "pending-login": {
            return "Pending MFA login";
        }
        case "recent-auth": {
            const disabledStateLabels = {
                deny: "MFA enrollment required",
                password: "Recent password when MFA is disabled",
                session: "Browser session when MFA is disabled",
            } as const;
            const disabledState = disabledStateLabels[access.whenMfaDisabled];
            const recentAuthentication = `${disabledState}; recent MFA when enabled`;
            if (
                access.capabilities === undefined &&
                access.principalKinds === undefined
            ) {
                return recentAuthentication;
            }
            return `${authenticatedPrincipalLabel(
                access.capabilities ?? [],
                access.principalKinds
            )}; ${recentAuthentication}`;
        }
        case "authenticated": {
            if (access.capabilityPolicy === "per-topic") {
                return `Authenticated; per-topic: ${access.capabilities.join(", ")}`;
            }
            return authenticatedPrincipalLabel(
                access.capabilities,
                access.principalKinds
            );
        }
        default: {
            const unsupportedAccess: never = access;
            throw new Error(`Unsupported contract access: ${String(unsupportedAccess)}`);
        }
    }
}

function documentHeader(title: string, source: string): string {
    return `# ${title}\n\n> Generated by \`${source}\`. Do not edit manually.\n\n`;
}

function errorsLabel(errors: readonly string[]): string {
    return errors.length === 0
        ? "None"
        : errors.map((error) => `\`${error}\``).join(", ");
}

function errorReasonsLabel(contract: ProcedureContract): string {
    return errorsLabel(contract.errorReasons ?? []);
}

/**
 * Renders the generated documentation index.
 * @returns Generated Markdown index.
 */
export function renderGeneratedIndex(): string {
    return `${documentHeader("Generated Dashboard Reference", "bun run generate docs")}The complete immutable reference is available in the authenticated Dashboard at \`/docs\`.\n\n- [tRPC procedures](procedures.md)\n- [Raw HTTP routes](raw-http.md)\n- [Raw HTTP OpenAPI 3.1](openapi.raw-http.json)\n- [Realtime events](realtime-events.md)\n- [Database schema](database.md)\n- [Browser routes and features](routes-and-features.md)\n- [Application configuration](configuration.md)\n- [Packages and runtime](packages-and-runtime.md)\n- [Transport schemas](schemas/)\n`;
}

/** One immutable Drizzle table projected into generated documentation. */
export interface DatabaseTableDocumentationInput {
    readonly checks: readonly { readonly expression: string; readonly name: string }[];
    readonly columns: readonly {
        readonly autoincrement: boolean;
        readonly defaultValue: string | null;
        readonly name: string;
        readonly notNull: boolean;
        readonly primaryKey: boolean;
        readonly type: string;
    }[];
    readonly name: string;
    readonly foreignKeys: readonly {
        readonly columns: readonly string[];
        readonly name: string;
        readonly onDelete: string;
        readonly onUpdate: string;
        readonly referencedColumns: readonly string[];
        readonly referencedTable: string;
    }[];
    readonly indexes: readonly {
        readonly columns: readonly string[];
        readonly name: string;
        readonly unique: boolean;
        readonly where: string | null;
    }[];
}

function databaseDefaultLabel(
    column: DatabaseTableDocumentationInput["columns"][number]
): string {
    if (column.autoincrement) return "Autoincrement";
    if (column.defaultValue === null) return "—";
    return `\`${markdownTableCell(column.defaultValue)}\``;
}

/**
 * Renders the authoritative SQLite table and column catalog.
 * @param tables Tables projected from the checked migration snapshot.
 * @returns Generated database Markdown.
 */
export function renderDatabase(
    tables: readonly DatabaseTableDocumentationInput[]
): string {
    if (tables.length === 0) throw new Error("Database table registry is empty");
    const names = tables.map(({ name }) => name);
    if (new Set(names).size !== names.length) {
        throw new Error("Database table registry contains duplicates");
    }
    const sections = tables
        .toSorted((left, right) => left.name.localeCompare(right.name))
        .map((table) => {
            const rows = table.columns.map(
                (column) =>
                    `| \`${markdownTableCell(column.name)}\` | \`${markdownTableCell(column.type)}\` | ${column.notNull ? "No" : "Yes"} | ${column.primaryKey ? "Yes" : "No"} | ${databaseDefaultLabel(column)} |`
            );
            const foreignKeys = table.foreignKeys.map(
                (foreignKey) =>
                    `| \`${markdownTableCell(foreignKey.name)}\` | \`${foreignKey.columns.map(markdownTableCell).join(", ")}\` | \`${markdownTableCell(foreignKey.referencedTable)}(${foreignKey.referencedColumns.map(markdownTableCell).join(", ")})\` | \`${markdownTableCell(foreignKey.onUpdate)}\` | \`${markdownTableCell(foreignKey.onDelete)}\` |`
            );
            const indexes = table.indexes.map(
                (index) =>
                    `| \`${markdownTableCell(index.name)}\` | \`${index.columns.map(markdownTableCell).join(", ")}\` | ${index.unique ? "Yes" : "No"} | ${index.where === null ? "—" : `\`${markdownTableCell(index.where)}\``} |`
            );
            const checks = table.checks.map(
                (check) =>
                    `| \`${markdownTableCell(check.name)}\` | \`${markdownTableCell(check.expression)}\` |`
            );
            return `## \`${markdownTableCell(table.name)}\`\n\n| Column | SQLite type | Nullable | Primary key | Default |\n| --- | --- | --- | --- | --- |\n${rows.join("\n")}\n\n### Foreign keys\n\n| Name | Columns | References | On update | On delete |\n| --- | --- | --- | --- | --- |\n${foreignKeys.length === 0 ? "| — | — | — | — | — |" : foreignKeys.join("\n")}\n\n### Indexes\n\n| Name | Columns | Unique | Predicate |\n| --- | --- | --- | --- |\n${indexes.length === 0 ? "| — | — | — | — |" : indexes.join("\n")}\n\n### Checks\n\n| Name | Expression |\n| --- | --- |\n${checks.length === 0 ? "| — | — |" : checks.join("\n")}`;
        });
    return `${documentHeader("Database Schema", "bun run generate docs")}This reference is generated from the exact Drizzle schema used by migrations and runtime composition.\n\n${sections.join("\n\n")}\n`;
}

/** Browser route metadata required by generated documentation. */
export interface BrowserRouteDocumentationInput {
    readonly access: "public" | "session";
    readonly featureOwner: string;
    readonly navigationLabel: string | null;
    readonly path: string;
    readonly summary: string;
}

/**
 * Renders the source-backed browser route and feature registry as Markdown.
 * @param routes Implemented browser routes and their feature metadata.
 * @returns Generated Markdown document.
 */
export function renderBrowserRoutes(
    routes: readonly BrowserRouteDocumentationInput[]
): string {
    if (routes.length === 0) throw new Error("Browser route registry is empty");
    const routePaths = routes.map(({ path }) => path);
    if (
        new Set(routePaths).size !== routePaths.length ||
        routes.some(
            ({ featureOwner, path, summary }) =>
                !path.startsWith("/") ||
                featureOwner.trim().length === 0 ||
                summary.trim().length === 0
        )
    ) {
        throw new Error("Browser route documentation metadata is invalid");
    }
    const rows = routes
        .toSorted((left, right) => left.path.localeCompare(right.path))
        .map(
            (route) =>
                `| \`${markdownTableCell(route.path)}\` | ${route.access === "public" ? "Public" : "Browser session"} | ${route.navigationLabel === null ? "Hidden" : markdownTableCell(route.navigationLabel)} | \`${markdownTableCell(route.featureOwner)}\` | ${markdownTableCell(route.summary)} |`
        );

    return `${documentHeader("Browser Routes and Features", "bun run generate docs")}| Path | Access | Navigation | Feature owner | Summary |\n| --- | --- | --- | --- | --- |\n${rows.join("\n")}\n`;
}

/** Registry metadata required to render one application configuration field. */
export interface ConfigurationDocumentationInput {
    readonly allowedValues: readonly string[] | null;
    readonly browserExposure: "none" | "presence-only" | "value";
    readonly defaultValue: string | null;
    readonly description: string;
    readonly environmentName: string;
    readonly field: string;
    readonly operationalEffect: string;
    readonly overridePolicy: {
        readonly development: boolean;
        readonly test: boolean;
    };
    readonly restartRequired: boolean;
    readonly required: boolean;
    readonly roles: readonly string[];
    readonly secret: boolean;
    readonly validationConstraints: string;
    readonly valueType: string;
}

function markdownTableCell(value: string): string {
    const backslash = String.fromCodePoint(92);
    return value
        .replaceAll(backslash, String.raw`\\`)
        .replaceAll("|", String.raw`\|`)
        .replaceAll(/\r?\n/gu, " ");
}

function assertNonEmptyString(value: unknown, label: string): asserts value is string {
    if (typeof value !== "string" || value.trim().length === 0) {
        throw new Error(`Application configuration metadata is missing ${label}`);
    }
}

function assertConfigurationMetadata(
    entry: ConfigurationDocumentationInput,
    index: number
): void {
    const prefix = `entry ${index}`;
    assertNonEmptyString(entry.environmentName, `${prefix}.environmentName`);
    assertNonEmptyString(entry.field, `${prefix}.field`);
    assertNonEmptyString(entry.valueType, `${prefix}.valueType`);
    assertNonEmptyString(entry.description, `${prefix}.description`);
    assertNonEmptyString(entry.operationalEffect, `${prefix}.operationalEffect`);
    assertNonEmptyString(entry.validationConstraints, `${prefix}.validationConstraints`);
    if (entry.defaultValue !== null && typeof entry.defaultValue !== "string") {
        throw new Error(
            `Application configuration metadata is missing ${prefix}.defaultValue`
        );
    }
    if (typeof entry.required !== "boolean") {
        throw new TypeError(
            `Application configuration metadata is missing ${prefix}.required`
        );
    }
    if (
        entry.allowedValues !== null &&
        (!Array.isArray(entry.allowedValues) ||
            entry.allowedValues.length === 0 ||
            entry.allowedValues.some(
                (allowedValue) =>
                    typeof allowedValue !== "string" || allowedValue.trim().length === 0
            ))
    ) {
        throw new Error(
            `Application configuration metadata is missing ${prefix}.allowedValues`
        );
    }
    if (
        !Array.isArray(entry.roles) ||
        entry.roles.length === 0 ||
        entry.roles.some((role) => typeof role !== "string" || role.trim().length === 0)
    ) {
        throw new Error(`Application configuration metadata is missing ${prefix}.roles`);
    }
    if (
        entry.browserExposure !== "none" &&
        entry.browserExposure !== "presence-only" &&
        entry.browserExposure !== "value"
    ) {
        throw new Error(
            `Application configuration metadata is missing ${prefix}.browserExposure`
        );
    }
    if (
        typeof entry.secret !== "boolean" ||
        typeof entry.restartRequired !== "boolean" ||
        typeof entry.overridePolicy !== "object" ||
        entry.overridePolicy === null ||
        typeof entry.overridePolicy.development !== "boolean" ||
        typeof entry.overridePolicy.test !== "boolean"
    ) {
        throw new Error(`Application configuration metadata is incomplete at ${prefix}`);
    }
    if (entry.secret && entry.browserExposure === "value") {
        throw new Error(
            `Secret application configuration metadata permits browser value exposure at ${prefix}`
        );
    }
}

function allowedValuesLabel(entry: ConfigurationDocumentationInput): string {
    if (entry.secret) return `\`${entry.valueType}\`; values withheld`;
    if (entry.allowedValues === null) return `\`${entry.valueType}\``;
    const allowedValues = entry.allowedValues
        .map((value) => `\`${markdownTableCell(value)}\``)
        .join(", ");
    return `\`${entry.valueType}\`; ${allowedValues}`;
}

function defaultBehaviorLabel(entry: ConfigurationDocumentationInput): string {
    if (!entry.required && entry.defaultValue === null) return "Optional; no default";
    if (entry.secret) {
        return entry.defaultValue === null
            ? "Required; value withheld"
            : "Default value withheld";
    }
    if (entry.defaultValue === null) return "Required";
    if (entry.defaultValue.length === 0) return "Empty by default";
    return `\`${markdownTableCell(entry.defaultValue)}\``;
}

function browserExposureLabel(
    exposure: ConfigurationDocumentationInput["browserExposure"]
): string {
    const labels = {
        none: "None",
        "presence-only": "Presence only",
        value: "Value",
    } as const;
    return labels[exposure];
}

function overridePolicyLabel(
    policy: ConfigurationDocumentationInput["overridePolicy"]
): string {
    if (policy.development && policy.test) return "Development and test";
    if (policy.development) return "Development only";
    if (policy.test) return "Test only";
    return "None";
}

/**
 * Renders immutable application configuration metadata as Markdown.
 * @param registry Authoritative application configuration registry.
 * @returns Generated Markdown document with secret values omitted.
 */
export function renderConfiguration(
    registry: readonly ConfigurationDocumentationInput[]
): string {
    if (registry.length === 0) {
        throw new Error("Application configuration registry is empty");
    }

    const environmentNames = new Set<string>();
    const fields = new Set<string>();
    for (const [index, entry] of registry.entries()) {
        assertConfigurationMetadata(entry, index);
        if (environmentNames.has(entry.environmentName) || fields.has(entry.field)) {
            throw new Error("Application configuration registry contains duplicates");
        }
        environmentNames.add(entry.environmentName);
        fields.add(entry.field);
    }

    const rows = registry
        .toSorted((left, right) =>
            left.environmentName.localeCompare(right.environmentName)
        )
        .map(
            (entry) =>
                `| \`${markdownTableCell(entry.environmentName)}\` | \`${markdownTableCell(entry.field)}\` | ${allowedValuesLabel(entry)} | ${markdownTableCell(entry.validationConstraints)} | ${defaultBehaviorLabel(entry)} | ${entry.roles.map((role) => `\`${markdownTableCell(role)}\``).join(", ")} | ${entry.secret ? "Yes" : "No"} | ${browserExposureLabel(entry.browserExposure)} | ${markdownTableCell(entry.operationalEffect)} | ${entry.restartRequired ? "Required" : "Not required"} | ${overridePolicyLabel(entry.overridePolicy)} | ${markdownTableCell(entry.description)} |`
        );

    return `${documentHeader("Application Configuration", "bun run generate docs")}Configuration metadata is generated from the immutable application registry. For secret fields, values, enumerated values, and defaults are never rendered.\n\n| Environment | Typed field | Type / enumerated values | Validation constraints | Default behavior | Process roles | Secret | Browser exposure | Operational effect | Restart | Development/test overrides | Description |\n| --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- |\n${rows.join("\n")}\n`;
}

/**
 * Renders procedure contracts as Markdown.
 * @param contracts Implemented procedure contracts.
 * @returns Generated Markdown document.
 */
export function renderProcedures(contracts: readonly ProcedureContract[]): string {
    const rows = contracts
        .toSorted((left, right) => left.name.localeCompare(right.name))
        .map(
            (contract) =>
                `| \`${contract.name}\` | ${contract.kind} | ${contract.domain} | ${accessLabel(contract.access)} | [input](./schemas/${contract.inputSchemaId}.schema.json) | [output](./schemas/${contract.outputSchemaId}.schema.json) | ${errorsLabel(contract.errors)} | ${errorReasonsLabel(contract)} | ${contract.summary} |`
        );

    return `${documentHeader("tRPC Procedures", "bun run generate docs")}| Procedure | Kind | Domain | Access | Input | Output | Expected errors | Client action reasons | Summary |\n| --- | --- | --- | --- | --- | --- | --- | --- | --- |\n${rows.join("\n")}\n`;
}

function rawHttpBodyLabel(body: RawHttpBodyContract): string {
    if (body.kind === "none") return "No body";
    if (body.kind === "websocket") {
        return `WebSocket \`${markdownTableCell(body.protocol)}\` — client ${body.clientMaximumMessageBytes} bytes, server ${body.serverMaximumMessageBytes} bytes per message`;
    }
    const contentTypes = body.contentTypes
        .map((contentType) => `\`${markdownTableCell(contentType)}\``)
        .join(", ");
    if (body.kind === "schema") {
        return `[schema](./schemas/${body.schemaId}.schema.json) — ${contentTypes}`;
    }
    const transfer = body.transfer === "buffered" ? "Buffered" : "Streamed";
    return `${transfer} binary, at most ${body.maximumBytes} bytes — ${contentTypes}`;
}

function rawHttpPathLabel(contract: RawHttpContract): string {
    if (contract.query === undefined || contract.query.parameters.length === 0) {
        return contract.path;
    }
    const query = contract.query.parameters
        .map((parameter) => {
            const value =
                parameter.values.length === 1
                    ? parameter.values[0]
                    : `{${parameter.values.join(",")}}`;
            return `${parameter.name}=${value}${parameter.required ? "" : "?"}`;
        })
        .join("&");
    return `${contract.path}?${query}`;
}

/**
 * Renders raw HTTP route contracts as Markdown.
 * @param contracts Implemented raw HTTP contracts.
 * @returns Generated Markdown document.
 */
export function renderRawHttp(contracts: readonly RawHttpContract[]): string {
    const rows = contracts
        .toSorted((left, right) =>
            `${left.path}:${left.method}`.localeCompare(`${right.path}:${right.method}`)
        )
        .map((contract) => {
            const range =
                contract.rangeRequests === "single-byte-range"
                    ? "Single byte range"
                    : "None";
            return `| ${contract.method} | \`${markdownTableCell(rawHttpPathLabel(contract))}\` | ${accessLabel(contract.access)} | ${contract.statusCodes.join(", ")} | ${rawHttpBodyLabel(contract.requestBody)} | ${rawHttpBodyLabel(contract.response)} | ${range} | ${contract.summary} |`;
        });

    return `${documentHeader("Raw HTTP Routes", "bun run generate docs")}| Method | Path | Access | Status | Request body | Response | Range requests | Summary |\n| --- | --- | --- | --- | --- | --- | --- | --- |\n${rows.join("\n")}\n`;
}

/**
 * Renders realtime topic contracts as Markdown.
 * @param contracts Implemented realtime contracts.
 * @returns Generated Markdown document.
 */
export function renderRealtimeEvents(
    contracts: readonly RealtimeEventContract[]
): string {
    const rows = contracts
        .toSorted((left, right) => left.topic.localeCompare(right.topic))
        .map(
            (contract) =>
                `| \`${contract.topic}\` | [payload](./schemas/${contract.payloadSchemaId}.schema.json) | \`${contract.snapshotProcedure}\` | ${contract.retention} | ${contract.summary} |`
        );
    const body =
        rows.length === 0
            ? "No standalone realtime topic references are published until their snapshot procedures are implemented.\n"
            : `| Topic | Payload | Snapshot | Retention | Summary |\n| --- | --- | --- | --- | --- |\n${rows.join("\n")}\n`;

    return `${documentHeader("Realtime Events", "bun run generate docs")}${body}`;
}

/** Direct dependency sections and Bun policy needed by generated documentation. */
export interface PackageDocumentationInput {
    dependencies: Readonly<Record<string, string>>;
    developmentDependencies: Readonly<Record<string, string>>;
    resolvedVersions: Readonly<Record<string, string>>;
    runtime: {
        channel: string;
        version: string;
    };
}

function packageRows(
    packages: Readonly<Record<string, string>>,
    resolvedVersions: Readonly<Record<string, string>>,
    scope: string
): string[] {
    return Object.entries(packages)
        .toSorted(([left], [right]) => left.localeCompare(right))
        .map(([name, declared]) => {
            const resolved = resolvedVersions[name];
            if (!resolved) {
                throw new Error(
                    `Direct package is missing from the Bun lockfile: ${name}`
                );
            }
            return `| \`${name}\` | \`${declared}\` | \`${resolved}\` | ${scope} |`;
        });
}

/**
 * Renders the runtime policy and exact direct package facts as Markdown.
 * @param input Runtime policy and package manifests.
 * @returns Generated Markdown document.
 */
export function renderPackagesAndRuntime(input: PackageDocumentationInput): string {
    const packageTable = [
        ...packageRows(input.dependencies, input.resolvedVersions, "runtime"),
        ...packageRows(
            input.developmentDependencies,
            input.resolvedVersions,
            "development"
        ),
    ].join("\n");

    return `${documentHeader("Packages and Runtime", "bun run generate docs")}## Bun\n\n| Fact | Value |\n| --- | --- |\n| Repository channel | \`${input.runtime.channel}\` |\n| Required runtime version | \`${input.runtime.version}\` |\n| Release identity | Exact revision recorded by each immutable release |\n\n## Direct packages\n\n| Package | Declared | Resolved | Scope |\n| --- | --- | --- | --- |\n${packageTable}\n`;
}
