[install]
peer = false

[test]
preload = ["./src/test/setup.ts"]
coverageSkipTestFiles = true
coveragePathIgnorePatterns = [
    "scripts/**",
    "src/**/*.d.ts",
    "src/**/*.stories.tsx",
    "src/**/storySupport/**",
    "src/**/test/**",
    "src/**/testSupport/**",
    "src/server/test/**",
    "src/test/**",
]

[serve.static]
plugins = [
    "./scripts/reactCompilerPlugin.ts",
    "./scripts/development/tanStackRouterHmrWorkaroundPlugin.ts",
    "bun-plugin-tailwind",
]
environment = "PUBLIC_*"
